obj-m  += mod81.o mod82.o mod83.o mod84.o mod85.o mod86.o mod87.o mod82_modify.o mod81_thread.o mod81_odd_even.o mod86_prac.o
 
ifdef ARCH
  #You can update your Beaglebone path here.
  KSRC = ../linux
else
  KSRC = /lib/modules/$(shell uname -r)/build
endif

mods:
	make -C $(KSRC)  M=$(shell pwd) modules
 
clean:
	make -C $(KSRC)  M=$(shell pwd) clean
